[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 30

[test-points]
Task 1 - PrecomputedWordGraph = task1,22
Task 2 - Variations = task2,22
Task 3 - Shortest Word Path = task3,22
Task 4 - PseudoWordGraph,1 = task4,22
Type-Checking = mypy,12
