[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 30

[test-points]
Task 1 - PrecomputedWordGraph = task1,1
Task 2 - Variations = task2,1
Task 3 - Shortest Word Path = task3,1
Task 4 - PseudoWordGraph,1 = task4,1
Type-Checking = mypy,1
