[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 5

[test-points]
Task 1 - to_base_n, from_base_n = task1,1
Task 2 - affordable_subsequences = task2,1
Task 3 - merge_dictionaries = task3,1
; Task 4 - conflicting_features = task4,1
Type-Checking = mypy,1
