[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 5

[test-points]
Task 1 - Mean, Median, Mode = task1,35
Task 2 - QuadTree Implementations = task2,35
; Task 3 - QuadTree GUI = task3,20
Type-Checking = mypy,10

