[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 5

[test-points]
Task 1 - Function Composition = task1,20
Task 2 - ConcatMap = task2,20
Task 3 - Tree Map and Reduce = task3,20
Task 4 - Decorators = task4,20
Task 5 - Simple TUI = task5,10
Type-Checking = mypy,10

