[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json
timeout = 5

[test-points]
Task 1 - TODO = task1,1
Task 2 - TODO = task2,1
Task 3 - TODO = task3,1
Task 4 - TODO = task4,1
Task 5 - TODO = task5,1
Type-Checking = mypy,1

