[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json

[test-points]
Task 1 = task1,30
Task 2 = task2,30
Task 3 = task3,30
Type-Checking = mypy,10
