[pytest]
addopts = --mypy --json-report --json-report-indent=2 --json-report-omit streams --json-report-file tests.json

[test-points]
Task 1 = task1,1
Task 2 = task2,1
Task 3 = task3,1
Type-Checking = mypy,1
